### PR TITLE
Add support for filament v3

### PR DESCRIPTION
**Pull request by mansoorkhan96**
This pull request upgrades the package to add support for Filament v3.

### CODE REVIEW

**Comment by mansoorkhan96** [comment]
@LukasFreyCZ The pull request is almost ready. The draft pagination just needs some love.

**Comment by mansoorkhan96** [comment]
#9

**Comment by mansoorkhan96** [comment]
@LukasFreyCZ PR is ready to be merged.

I have tweaked the revisions pagination to look better. I have tested quite well on my side, but still appreciate someone to test/review.

### Light Theme:
image

### Dark Theme:
image

**Comment by lukas-frey** [comment]
Thanks a lot! I will have a look at it later this evening. :)

**Pull request merged**
